config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :sports
  resources :teams
  resources :gamedays, except: [:create]
  resources :matchups
  resources :results
  resources :rankings
  resources :game, controller: :matchups
  resources :public, only: [:index, :show]

  post 'gamedays', as: :gameday_sets, to: 'gamedays#create_many'
  post 'games', as: :game_sets, to: 'matchups#create_many'

  post 'matchups/save', to: 'matchups#save', as: :matchups_save
  get 'matchups/:id/reverse', to: 'matchups#reverse', as: :matchup_reverse
  post 'results/create', to: 'results#collection_create', as: :results_create

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new', via: :get
  match '/help', to: 'static_pages#help', via: :get

  resources :sessions do
    collection do
      get 'forgot_password', to: 'sessions#forgot_password'
      post 'forgot_password', to: 'sessions#password_reset'
    end
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :rights_group_id, inclusion: { in: 0..2 }

  before_validation on: :create do
    generate_password if self.password.nil?
  end

  def rights_group
    @rights_group ||= RightsGroup.find rights_group_id
  end

  def generate_password
    #self.password = "test"
    #self.password = SecureRandom.urlsafe_base64(6) # TODO: DO NOT FORGET ABOUT THIS
    self.password = self.generate_readable_password(8) # check out lib/generate_readable_password.rb
    
    @password_new = self.password #since only a hash will be saved in the db
  end

  def password_new
    return @password_new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #skip_authorization_check
  authorize_resource
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      # right now emails are delivered immediately
      # this is considered bad practice
      # TODO: https://devcenter.heroku.com/articles/delayed-job
      UserMailer.new_user(@user).deliver
      redirect_to users_path, success: I18n.t(:object_created)
    else
      flash.now.alert = I18n.t :object_create_failed
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params then
      redirect_to users_path, success: I18n.t(:object_updated)
    else
      flash.now.alert = I18n.t :object_update_failed
      render :edit
    end
  end

  def destroy
    unless user_session.user.id.to_s == params[:id]
      if User.destroy params[:id]
        redirect_to users_path, success: I18n.t(:object_deleted)
        return
      end
    end
    redirect_to users_path, alert: I18n.t(:object_delete_failed)
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :rights_group_id, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render 'shared/form_errors', obj: @user %>
<%= form_for user, builder: BootstrapFormBuilder do |f| %>
  <%= f.bs_text_field(:first_name) %>
  <%= f.bs_text_field(:last_name) %>
  <%= f.bs_text_field(:email) %>
  <%= f.bs_text_field(:password, placeholder: "AUTOMATISCH GENERIERT WENN LEER") %>
  <%= f.bs_select(:rights_group_id, RightsGroup.all_for_select) %>
  <%= f.bs_submit("SUBMIT") %>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form', locals: { user: @user } %>

app/views/users/index.html.erb
<h1><%= t :users_index %></h1>

<div class="responsive-table">
  <table class="table table-condensed table-responsive">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :first_name %>
        <th><%= User.human_attribute_name :last_name %>
        <th><%= User.human_attribute_name :email %>
        <th><%= User.human_attribute_name :rights_group %>
        <th><%= t :actions %>
        <th>
    <tbody>
      <% @users.each do |obj| %>
        <tr>
          <td><%= obj.first_name %>
          <td><%= obj.last_name %>
          <td><%= obj.email %>
          <td><%= obj.rights_group.name %>
          <td><%= link_to(t(:update), edit_user_path(obj)) %>
          <td><%= link_to(t(:delete), obj, method: :delete, data: { confirm: t(:delete_confirm) }) %>
      <% end %>
  </table>
</div>

app/views/users/new.html.erb
<%= render partial: 'form', locals: { user: @user } %>