config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :sports
  resources :teams
  resources :gamedays, except: [:create]
  resources :matchups
  resources :results
  resources :rankings
  resources :game, controller: :matchups
  resources :public, only: [:index, :show]

  post 'gamedays', as: :gameday_sets, to: 'gamedays#create_many'
  post 'games', as: :game_sets, to: 'matchups#create_many'

  post 'matchups/save', to: 'matchups#save', as: :matchups_save
  get 'matchups/:id/reverse', to: 'matchups#reverse', as: :matchup_reverse
  post 'results/create', to: 'results#collection_create', as: :results_create

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new', via: :get
  match '/help', to: 'static_pages#help', via: :get

  resources :sessions do
    collection do
      get 'forgot_password', to: 'sessions#forgot_password'
      post 'forgot_password', to: 'sessions#password_reset'
    end
  end
  

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  authorize_resource :game, :league, :parent => false

  def new
  end

  def create
  end

  def collection_create
    Game.add_results(params[:score])
    redirect_to results_path, success: t(:object_updated)
  end

  def index
    sport_id = sport_id_filter_default request[:filter]
    @leagues = League.where(sport_id: sport_id).order(number: :asc)
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end


  private
  def result_params
    #params.require(:team).permit(:name, :email, :sport_id, :league_id, :sport_id)
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<% if can? :change_all_results, game or (Date.yesterday() - game.gameday.date < 1) %>
  <%= render partial: "form_editable", locals: { game: game }%>
<% else %>
  <%= render partial: "form_static", locals: { game: game }%>
<% end %>

app/views/results/_form_editable.html.erb
<% for i in 1..(game.league.sport.number_of_sets) %>
  <div class="row">
    <div class="col-md-5 col-xs-5">
      <%= text_field_tag "score[#{game.id}][#{i}][]", game.gamesets.where(number: i).first.points_team_1, class: "form-control input-sm" %>
    </div>
    <div class="col-md-1 col-xs-1 text-center">
       : 
    </div>
    <div class="col-md-5 col-xs-5">
      <%= text_field_tag "score[#{game.id}][#{i}][]", game.gamesets.where(number: i).first.points_team_2, class: "form-control input-sm" %>
    </div>
  </div>
<% end %>

app/views/results/_form_static.html.erb
<% for i in 1..(game.league.sport.number_of_sets) %>
  <% if not game.gamesets.where(number: i).first.points_team_1.nil? and not game.gamesets.where(number: i).first.points_team_2.nil? %>
    (<%= game.gamesets.where(number: i).first.points_team_1 %>
    <%= " : " %>
    <%= game.gamesets.where(number: i).first.points_team_2 %>) 
  <% end %>
<% end %>

app/views/results/index.html.erb
<%= render partial: 'shared/filter', locals: { obj: Sport.all, label: t(:sports_filter) } %>

<%= form_tag results_create_path do %>
  <% @leagues.each do |l| %>
    <h1>
      <%= "#{l.number}. Liga" %>
      <%= submit_tag t(:submit), class: "btn btn-primary" %>
    </h1>
    <% l.games.join_gamedays.each do |obj| %>
      <div class="well well-sm">
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <%= l obj.gameday.date, format: :short %>:
            <% if obj.team_is_winner?(obj.team_1_id) %>
              <strong>
            <% end %>
            <%= "#{obj.team_1.name}" %>
            <% if obj.team_is_winner?(obj.team_1_id) %>
              </strong>
            <% end %>
             : 
            <% if obj.team_is_winner?(obj.team_2_id) %>
              <strong>
            <% end %>
            <%= "#{obj.team_2.name}" %>
            <% if obj.team_is_winner?(obj.team_2_id) %>
              </strong>
            <% end %>
          </div>
          <div class="col-xs-12 col-md-6">
            <%= render partial: 'form', locals: { game: obj } %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>