config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :sports
  resources :teams
  resources :gamedays, except: [:create]
  resources :matchups
  resources :results
  resources :rankings
  resources :game, controller: :matchups
  resources :public, only: [:index, :show]

  post 'gamedays', as: :gameday_sets, to: 'gamedays#create_many'
  post 'games', as: :game_sets, to: 'matchups#create_many'

  post 'matchups/save', to: 'matchups#save', as: :matchups_save
  get 'matchups/:id/reverse', to: 'matchups#reverse', as: :matchup_reverse
  post 'results/create', to: 'results#collection_create', as: :results_create

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new', via: :get
  match '/help', to: 'static_pages#help', via: :get

  resources :sessions do
    collection do
      get 'forgot_password', to: 'sessions#forgot_password'
      post 'forgot_password', to: 'sessions#password_reset'
    end
  end
  

end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  authorize_resource :league, :game, :parent => false

  def new
  end

  def create_many
    @game_set = GameSet.new(gameset_params)
    if @game_set.save
      redirect_to({ action: :index }, success: t(:object_created))
    else
      redirect_to({ action: :index }, alert: t(:object_create_failed))
    end
  end

  def save
    params[:date].each do |game_id, gameday_id|
      game = Game.find(game_id)
      game.update_attributes(gameday_id: gameday_id, order: params[:order][game_id])
      redirect_to(matchups_path, alert: t(:object_create_failed)) unless game.errors.empty?
    end
    redirect_to matchups_path, success: t(:object_created)
  end

  def edit
  end

  def update
  end

  def index
    sport_id = sport_id_filter_default request[:filter]
    @leagues = League.where(sport_id: sport_id).order(number: :asc)
    @game_set = GameSet.new
    @game_set.games = Game.where(league_id: @leagues)
  end

  def destroy
    destroy_action(Game, filter: Game.find(params[:id]).league.sport_id)
  end


  private
  def game_params
    #params.require(:game).permit(:gameday_id, :team_1_number, :team_2_number)
  end

  def gameset_params
    params.require(:game_set).permit(games_attributes: [:id, :gameday_id, :team_1_number, :team_2_number])
  end
end

app/helpers/matchups_helper.rb
module MatchupsHelper
end

app/views/matchups/_form_generate.html.erb
<%= form_tag({}, {class: "form-inline"}) do %>
  <div class="form-group">
    <h4><%= "#{t(:matchups_generate)}: " %></h4>
      <%= collection_select(:league, :id, League.where(sport_id: Sport.selected).order(:number), :id, :display_name, { }, class: "form-control" ) %>
    <%= submit_tag t(:generate), class: "btn btn-default" %>
      <%= hidden_field :sport, :id, value: request[:filter] %>
  </div>
<% end %>

app/views/matchups/_old_index.html.erb
<p>
  <%= render partial: 'shared/filter', locals: { obj: Sport.all, label: t(:sports_filter) } %>
</p>
<p>
  <%= render partial: 'form_generate' %>
</p>

<%= form_tag matchups_save_path do %>
  <% @leagues.each do |l| %>
    <h1><%= "#{l.number}. Liga" %>
      <%= submit_tag t(:submit), class: "btn btn-primary" %>
    </h1>
      <% l.games.join_left_gamedays.each do |obj| %>
        <div class="well well-sm">
          <div class="row">
            <div class="col-xs-8 col-md-9 form-inline">
              <%= hidden_field_tag "order[#{obj.id}]", obj.order %>
              (<span id="<%= "order_tag_#{obj.id}" %>"><%= obj.order %></span>)
              <strong><%= "#{obj.team_1.display_name} : #{obj.team_2.display_name}" %></strong>
            </div>
            <!--<div class="col-xs-4 col-md-3 form-inline text-right">
              <%= text_field_tag "order[#{obj.id}]", obj.order, class: "form-control input-sm" %>
            </div>-->
            <div class="col-xs-4 col-md-3 text-right">
              <%= link_to(t(:reverse), matchup_reverse_path(obj)) %>
              <%= link_to(t(:delete), matchup_path(obj), method: :delete, data: { confirm: t(:delete_confirm) }) %>
            </div>
          </div>
          <div class="row">
            <% l.gamedays.order(:date).each do |gd| %>
              <div class="col-md-2">
                <%= label_tag "date_#{obj.id}_#{gd.id}", style: "font-weight:normal;" do %>
                  <%= radio_button_tag "date[#{obj.id}]", gd.id, (obj.gameday_id == gd.id) %>
                  <%= gd.date %>
                <% end %>
              </div> 
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <%= hidden_field :sport, :id, value: request[:filter] %>
<% end %>

app/views/matchups/index.html.erb
<p>
  <%= render partial: 'shared/filter', locals: { obj: Sport.all, label: t(:sports_filter) } %>
</p>

<%= form_for @game_set do |f| %>
  <% @leagues.each do |l| %>
    <h1><%= l.number %>. Liga</h1>
    <% l.gamedays.each do |gd| %>
      <h4><%= "#{gd.date} #{gd.location}" %></h4>
      <%= link_to 'Spiel hinzufügen', '#', class: 'addgame', data: { id: gd.id } %>
      <div class="game-set" id="<%= gd.id %>">
        <%= f.fields_for :games, f.object.games.where(gameday_id: gd.id) do |game| %>
          <div class="form-group form-inline">
            <%= game.text_field :team_1_number, class: 'form-control', name: 'game_set[games_attributes][][team_1_number]' %>
            <span> : </span>
            <%= game.text_field :team_2_number, class: 'form-control', name: 'game_set[games_attributes][][team_2_number]' %>
            <%= link_to(t(:delete), game.object, method: :delete, data: { confirm: t(:delete_confirm) }) %>
            <%= game.hidden_field :gameday_id, name: 'game_set[games_attributes][][gameday_id]' %>
            <%= game.hidden_field :id, name: 'game_set[games_attributes][][id]' %>
          </div> 
        <% end %>
      </div>
    <% end %>
    <%= submit_tag(t(:submit), class: 'btn btn-primary') %>
  <% end %>
<% end %>