config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :sports
  resources :teams
  resources :gamedays, except: [:create]
  resources :matchups
  resources :results
  resources :rankings
  resources :game, controller: :matchups
  resources :public, only: [:index, :show]

  post 'gamedays', as: :gameday_sets, to: 'gamedays#create_many'
  post 'games', as: :game_sets, to: 'matchups#create_many'

  post 'matchups/save', to: 'matchups#save', as: :matchups_save
  get 'matchups/:id/reverse', to: 'matchups#reverse', as: :matchup_reverse
  post 'results/create', to: 'results#collection_create', as: :results_create

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new', via: :get
  match '/help', to: 'static_pages#help', via: :get

  resources :sessions do
    collection do
      get 'forgot_password', to: 'sessions#forgot_password'
      post 'forgot_password', to: 'sessions#password_reset'
    end
  end
  

end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| -%>
  <div class="<%= bootstrap_flash_class_for name %> alert-dismissible">
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only"><%= t :close %></span>
  </button>
  <%= msg %>
  </div>
<% end %>

app/views/layouts/_meta_tags.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"> <%# Bootstrap mobile first feature %>

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%#= link_to 'Home', root_path, class: "navbar-brand" %>
  </div>
  <div class="navbar-collapse collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
       <%= build_top_nav([:users, :sports, :teams, :gamedays, :matchups, :results, :rankings]) %>
      <li class="<%= current_page?(controller: :static_pages, action: :help) ? 'active' : '' %>"><%= link_to(action_label_for(:static_pages, :help), help_path) %></li>
      <li><%= link_to(t(:logout), logout_path) if user_session.authenticated? %></li>
    </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <%= render 'layouts/meta_tags' %>
  <title>WinAdmin v2.0</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <%= render 'layouts/navbar' %>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <%= build_sub_nav({users: [:index, :new], sports: [:index, :new], teams: [:index, :new], gamedays: [:index, :new], matchups: [:index], results: []}) %>
        </ul>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= render 'layouts/flash' %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<head>
  <%= render 'layouts/meta_tags' %>
  <%= stylesheet_link_tag  'http://www.gltv.ch/Portals/_default/Skins/gltv/assets/winadmin.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= yield %>
</body>